/**
 * Layer 3 — starter product-type configs composed from Layer 1 modules.
 * Only types with validated V2.3.5 scoring assumptions.
 */

const CANONICAL_COOKWARE_FIXTURE_REFS = [
  'scripts/test-inert-cookware-canonical.mjs',
  'scripts/test-compound-cookware-material.mjs',
  'scripts/test-ceramic-nonstick-canonical.mjs',
  'scripts/test-stainless-18-10-canonical.mjs',
]

/** @type {import('../schema.mjs').ProductTypeRegistryConfig[]} */
export const STARTER_PRODUCT_TYPE_CONFIGS = [
  {
    registry_key: 'kitchen.cookware.fry_pan',
    category: 'Kitchen',
    subcategory: 'Cookware',
    product_type: 'Fry pan',
    subcategory_aliases: [
      'cookware',
      'frying_pan',
      'frying_pan_/_skillet',
      'fry_pan',
      'skillet',
      'saucepan',
      'saute_pan',
      'sauté_pan',
      'stockpot',
      'dutch_oven',
      'wok',
      'griddle',
      'grill_pan',
      'cookware_set',
      'nonstick_skillet',
      'ceramic_nonstick_skillet',
      'ceramic_nonstick_frying_pan',
      'nonstick_frying_pan',
    ],
    contact_model_refs: ['food_contact', 'indirect_contact', 'non_contact_internal_structural'],
    exposure_modifier_refs: ['heat', 'fatty', 'acidic', 'repeated_daily_use'],
    component_schema: [
      { role_ref: 'primary_contact_surface', material_class_refs: ['stainless_steel', 'cast_iron_carbon_steel', 'ceramic_enamel', 'coated_metals'] },
      { role_ref: 'coating_lining', material_class_refs: ['ceramic_enamel', 'plastics_resins'] },
      { role_ref: 'handle_grip', material_class_refs: ['stainless_steel', 'silicone'] },
      { role_ref: 'internal_core', material_class_refs: ['aluminum', 'cast_iron_carbon_steel', 'coated_metals'] },
    ],
    material_class_refs: ['stainless_steel', 'cast_iron_carbon_steel', 'aluminum', 'ceramic_enamel', 'coated_metals', 'silicone'],
    chemical_family_refs: ['pfas', 'unknown_proprietary_additive'],
    claim_family_refs: ['pfas_free', 'pfoa_free', 'nonstick_performance'],
    required_evidence_fields: [
      'material.primary_contact_raw',
      'material.primary_contact_canonical',
      'material.substrate_canonical',
      'material.coating_modifier_canonical',
      'material.pfas_status',
    ],
    disclosure_rule_refs: ['cookware_transparency', 'inert_material_public_copy'],
    matrix_key: 'cookware',
    source_requirements: ['retailer_primary', 'manufacturer'],
    scoring_assumption_ref: 'v2.3.5.cookware',
    display_template_refs: ['cookware_description', 'cookware_use_conditions'],
    fixture_refs: CANONICAL_COOKWARE_FIXTURE_REFS,
    secondary_material_policy_ref: 'cookware_show_internal_cores',
  },
  {
    registry_key: 'kitchen.drinkware.water_bottle',
    category: 'Kitchen',
    subcategory: 'Drinkware',
    product_type: 'Water bottle',
    subcategory_aliases: ['water_bottle'],
    contact_model_refs: ['drink_contact', 'indirect_contact'],
    exposure_modifier_refs: ['repeated_daily_use', 'wet', 'heat', 'freezing'],
    component_schema: [
      { role_ref: 'primary_contact_surface', material_class_refs: ['stainless_steel', 'plastics_resins', 'glass', 'silicone'] },
      { role_ref: 'lid_cap', material_class_refs: ['plastics_resins', 'stainless_steel'] },
      { role_ref: 'seal_gasket', material_class_refs: ['silicone', 'rubber_elastomers'] },
      { role_ref: 'straw_spout', material_class_refs: ['plastics_resins', 'silicone'] },
    ],
    material_class_refs: ['stainless_steel', 'plastics_resins', 'glass', 'silicone', 'rubber_elastomers'],
    chemical_family_refs: ['bisphenols_bpa_bps', 'phthalates'],
    claim_family_refs: ['bpa_free', 'food_grade'],
    required_evidence_fields: ['material.primary_contact_raw', 'material.primary_contact_canonical'],
    disclosure_rule_refs: ['drinkware_transparency'],
    matrix_key: 'water_bottles',
    source_requirements: ['retailer_primary'],
    scoring_assumption_ref: 'v2.3.5.water_bottles',
    display_template_refs: ['drinkware_description'],
    fixture_refs: [],
    secondary_material_policy_ref: 'drinkware_suppress_internal_cores',
  },
  {
    registry_key: 'kitchen.drinkware.tumbler',
    category: 'Kitchen',
    subcategory: 'Drinkware',
    product_type: 'Tumbler',
    subcategory_aliases: ['drinkware', 'travel_mug', 'tumbler', 'cup', 'mug'],
    contact_model_refs: ['drink_contact', 'indirect_contact'],
    exposure_modifier_refs: ['repeated_daily_use', 'wet', 'heat', 'freezing'],
    component_schema: [
      { role_ref: 'primary_contact_surface', material_class_refs: ['stainless_steel', 'plastics_resins', 'glass', 'silicone'] },
      { role_ref: 'lid_cap', material_class_refs: ['plastics_resins', 'stainless_steel'] },
      { role_ref: 'seal_gasket', material_class_refs: ['silicone', 'rubber_elastomers'] },
      { role_ref: 'straw_spout', material_class_refs: ['plastics_resins', 'silicone'] },
    ],
    material_class_refs: ['stainless_steel', 'plastics_resins', 'glass', 'silicone', 'rubber_elastomers'],
    chemical_family_refs: ['bisphenols_bpa_bps', 'phthalates'],
    claim_family_refs: ['bpa_free', 'food_grade'],
    required_evidence_fields: ['material.primary_contact_raw', 'material.primary_contact_canonical'],
    disclosure_rule_refs: ['drinkware_transparency'],
    matrix_key: 'drinkware',
    source_requirements: ['retailer_primary'],
    scoring_assumption_ref: 'v2.3.5.drinkware',
    display_template_refs: ['drinkware_description'],
    fixture_refs: [],
    secondary_material_policy_ref: 'drinkware_suppress_internal_cores',
  },
  {
    registry_key: 'kitchen.food_storage.storage_container',
    category: 'Kitchen',
    subcategory: 'Food storage',
    product_type: 'Storage container',
    subcategory_aliases: ['food_storage', 'glass_containers'],
    contact_model_refs: ['food_contact', 'indirect_contact'],
    exposure_modifier_refs: ['heat', 'microwave', 'freezing', 'long_duration_storage', 'repeated_daily_use'],
    component_schema: [
      { role_ref: 'primary_contact_surface', material_class_refs: ['plastics_resins', 'glass', 'silicone'] },
      { role_ref: 'lid_cap', material_class_refs: ['plastics_resins'] },
      { role_ref: 'seal_gasket', material_class_refs: ['silicone', 'rubber_elastomers'] },
    ],
    material_class_refs: ['plastics_resins', 'glass', 'silicone', 'rubber_elastomers'],
    chemical_family_refs: ['bisphenols_bpa_bps', 'phthalates', 'styrene'],
    claim_family_refs: ['bpa_free', 'microwave_safe'],
    required_evidence_fields: ['material.primary_contact_raw', 'material.primary_contact_canonical'],
    disclosure_rule_refs: ['food_storage_transparency'],
    matrix_key: 'food_storage',
    source_requirements: ['retailer_primary'],
    scoring_assumption_ref: 'v2.3.5.food_storage',
    display_template_refs: ['food_storage_description'],
    fixture_refs: [],
    secondary_material_policy_ref: 'default_suppress_internal_cores',
  },
  {
    registry_key: 'kitchen.utensils.spatula_or_cutting_board',
    category: 'Kitchen',
    subcategory: 'Utensils',
    product_type: 'Spatula or cutting board',
    subcategory_aliases: ['cooking_utensils', 'cutting_boards', 'utensils', 'spatula', 'cutting_board'],
    contact_model_refs: ['food_contact', 'indirect_contact'],
    exposure_modifier_refs: ['heat', 'abrasion', 'repeated_daily_use'],
    component_schema: [
      { role_ref: 'primary_contact_surface', material_class_refs: ['plastics_resins', 'stainless_steel', 'silicone'] },
      { role_ref: 'handle_grip', material_class_refs: ['plastics_resins', 'silicone', 'stainless_steel'] },
    ],
    material_class_refs: ['plastics_resins', 'stainless_steel', 'silicone', 'rubber_elastomers'],
    chemical_family_refs: ['pfas', 'melamine_formaldehyde'],
    claim_family_refs: ['food_grade'],
    required_evidence_fields: ['material.primary_contact_raw', 'material.primary_contact_canonical'],
    disclosure_rule_refs: ['utensils_transparency'],
    matrix_key: 'cooking_utensils',
    source_requirements: ['retailer_primary'],
    scoring_assumption_ref: 'v2.3.5.utensils',
    display_template_refs: ['utensils_description'],
    fixture_refs: [],
    secondary_material_policy_ref: 'default_suppress_internal_cores',
  },
  {
    registry_key: 'textiles.bedding.mattress_protector',
    category: 'Textiles',
    subcategory: 'Bedding',
    product_type: 'Mattress protector',
    subcategory_aliases: ['textiles', 'bedding', 'mattress_protector'],
    contact_model_refs: ['skin_contact_leave_on', 'child_contact'],
    exposure_modifier_refs: ['long_duration_storage', 'repeated_daily_use', 'wet'],
    component_schema: [
      { role_ref: 'primary_contact_surface', material_class_refs: ['textiles', 'plastics_resins'] },
      { role_ref: 'exterior_layer', material_class_refs: ['textiles'] },
    ],
    material_class_refs: ['textiles', 'plastics_resins'],
    chemical_family_refs: ['flame_retardants', 'pfas'],
    claim_family_refs: ['waterproof', 'hypoallergenic'],
    required_evidence_fields: ['material.primary_contact_raw'],
    disclosure_rule_refs: ['textiles_transparency'],
    matrix_key: 'textiles',
    source_requirements: ['manufacturer'],
    scoring_assumption_ref: 'v2.3.5.textiles',
    display_template_refs: ['textiles_description'],
    fixture_refs: [],
    secondary_material_policy_ref: 'default_suppress_internal_cores',
  },
  {
    registry_key: 'toys.infant.teether',
    category: 'Toys',
    subcategory: 'Infant',
    product_type: 'Teether',
    subcategory_aliases: ['baby_products', 'infant', 'teether'],
    contact_model_refs: ['mouth_contact', 'child_contact'],
    exposure_modifier_refs: ['repeated_daily_use', 'wet', 'abrasion'],
    component_schema: [
      { role_ref: 'primary_contact_surface', material_class_refs: ['silicone', 'plastics_resins', 'rubber_elastomers'] },
    ],
    material_class_refs: ['silicone', 'plastics_resins', 'rubber_elastomers'],
    chemical_family_refs: ['bisphenols_bpa_bps', 'phthalates', 'pvc_vinyl_plasticizers'],
    claim_family_refs: ['bpa_free', 'food_grade'],
    required_evidence_fields: ['material.primary_contact_raw'],
    disclosure_rule_refs: ['infant_oral_transparency'],
    matrix_key: 'infant_oral',
    source_requirements: ['manufacturer'],
    scoring_assumption_ref: 'v2.3.5.infant_oral',
    display_template_refs: ['infant_oral_description'],
    fixture_refs: [],
    secondary_material_policy_ref: 'default_suppress_internal_cores',
  },
  {
    registry_key: 'personal_care.rinse_off.shampoo',
    category: 'Personal care',
    subcategory: 'Rinse-off',
    product_type: 'Shampoo',
    subcategory_aliases: ['shampoo', 'rinse_off', 'hair_care'],
    contact_model_refs: ['skin_contact_rinse_off'],
    exposure_modifier_refs: ['rinse_off', 'wet', 'repeated_daily_use'],
    component_schema: [
      { role_ref: 'consumable_contact_medium', material_class_refs: ['plastics_resins'] },
      { role_ref: 'packaging', material_class_refs: ['plastics_resins', 'paper_cardboard'] },
    ],
    material_class_refs: ['plastics_resins', 'paper_cardboard'],
    chemical_family_refs: ['parabens', 'phthalates', 'unknown_proprietary_additive'],
    claim_family_refs: ['fragrance_free', 'sulfate_free'],
    required_evidence_fields: ['material.primary_contact_raw'],
    disclosure_rule_refs: ['rinse_off_transparency'],
    matrix_key: 'rinse_off',
    source_requirements: ['manufacturer'],
    scoring_assumption_ref: 'v2.3.5.rinse_off',
    display_template_refs: ['rinse_off_description'],
    fixture_refs: [],
    secondary_material_policy_ref: 'default_suppress_internal_cores',
  },
]
