begin;

truncate table public.score_details restart identity cascade;
truncate table public.categories restart identity cascade;
truncate table public.products restart identity cascade;

insert into public.products (
  product_name,
  brand,
  category,
  subcategory,
  description,
  pac_safety_score,
  tier,
  score_basis,
  primary_material,
  secondary_material,
  bpa_free,
  phthalate_free_claim,
  amazon_url,
  affiliate_link,
  target_url,
  walmart_url,
  other_retailer_label,
  other_retailer_url,
  active
) values
(
  'Hydro Flask 21oz Standard Mouth Water Bottle',
  'Hydro Flask',
  'Kitchen',
  'Water Bottles and Drinkware',
  'Hydro Flask is one of the gold standards in safe hydration. The interior is food grade 18/8 stainless steel which does not leach phthalates bisphenols or any plastic-associated chemicals into your water. The double wall vacuum insulation keeps drinks cold for 24 hours and hot for 12 without any plastic lining. The lid contains BPA free plastic components but liquid contact with plastic is minimal given the stainless steel body. A minor deduction from a perfect score reflects the plastic lid components that come into occasional liquid contact.',
  95,
  'Excellent',
  'Based on Materials Science',
  '18/8 Stainless Steel',
  'BPA Free Plastic Lid',
  'Yes',
  'Unknown',
  'https://www.amazon.com/s?k=Hydro+Flask+21oz+Standard+Mouth+Water+Bottle',
  'https://www.amazon.com/s?k=Hydro+Flask+21oz+Standard+Mouth+Water+Bottle',
  null,
  'https://www.walmart.com/ip/Hydro-Flask-Standard-Mouth-Water-Bottle-with-Flex-Cap-Black-21oz-621ml/8381206002',
  null,
  null,
  true
),
(
  'YETI Rambler 26oz Stainless Steel Bottle',
  'YETI',
  'Kitchen',
  'Water Bottles and Drinkware',
  'YETI has built its reputation on rugged performance and the Rambler delivers on PAC safety as well. The interior is 18/8 food grade stainless steel with no plastic lining — your water never touches plastic. The Chug Cap keeps liquid contact with plastic minimal and all plastic components are BPA free. YETI is transparent about their materials and explicitly markets products as free from BPA and other harmful chemicals.',
  93,
  'Excellent',
  'Based on Materials Science',
  '18/8 Stainless Steel',
  'BPA Free Plastic Chug Cap',
  'Yes',
  'Unknown',
  'https://www.amazon.com/s?k=YETI+Rambler+26oz+Stainless+Steel+Bottle',
  'https://www.amazon.com/s?k=YETI+Rambler+26oz+Stainless+Steel+Bottle',
  null,
  'https://www.walmart.com/ip/Yeti-Rambler-26oz-Bottle/28383528573',
  null,
  null,
  true
),
(
  'Klean Kanteen TKWide 20oz Insulated Bottle',
  'Klean Kanteen',
  'Kitchen',
  'Water Bottles and Drinkware',
  'Klean Kanteen has been one of the most trusted names in plastic-free hydration. The TKWide uses food grade 18/8 stainless steel throughout with no plastic lining. The brand has an explicit commitment to PAC-free materials and is one of the few companies to proactively test their products for chemical migration. At 94 this is one of the highest scoring bottles in our database.',
  94,
  'Excellent',
  'Based on Materials Science',
  '18/8 Stainless Steel',
  'BPA Free Plastic Cap',
  'Yes',
  'Yes',
  'https://www.amazon.com/s?k=Klean+Kanteen+TKWide+20oz+Insulated+Bottle',
  'https://www.amazon.com/s?k=Klean+Kanteen+TKWide+20oz+Insulated+Bottle',
  'https://www.target.com/p/klean-kanteen-20oz-tkwide-insulated-stainless-steel-water-bottle-with-cafe-cap/-/A-82748478',
  'https://www.walmart.com/ip/Klean-Kanteen-TKWide-Insulated-Water-Bottle-with-Twist-Cap-Stainless-Steel-Water-Bottle-20-Oz-Black/6410129654',
  null,
  null,
  true
),
(
  'CamelBak Chute Mag 32oz Stainless Steel',
  'CamelBak',
  'Kitchen',
  'Water Bottles and Drinkware',
  'The CamelBak Chute Mag combines excellent PAC safety with an innovative magnetic lid design. The stainless steel interior is food grade 18/8 with no plastic lining and all materials are BPA free. The magnetic cap keeps the lid secured away from the drinking spout so there is minimal plastic to liquid contact during use.',
  91,
  'Excellent',
  'Based on Materials Science',
  '18/8 Stainless Steel',
  'BPA Free Plastic Magnetic Lid',
  'Yes',
  'Unknown',
  'https://www.amazon.com/s?k=CamelBak+Chute+Mag+32oz+Stainless+Steel',
  'https://www.amazon.com/s?k=CamelBak+Chute+Mag+32oz+Stainless+Steel',
  'https://www.target.com/p/camelbak-32oz-chute-mag-vacuum-insulated-stainless-steel-water-bottle-beige/-/A-85576851',
  'https://www.walmart.com/ip/Camelbak-Chute-Mag-Stainless-Steel-Vacuum-Insulated-Bottle/5244933685',
  null,
  null,
  true
),
(
  'Owala FreeSip 24oz Insulated Stainless Steel',
  'Owala',
  'Kitchen',
  'Water Bottles and Drinkware',
  'The Owala FreeSip is one of the most popular water bottles on the market. The stainless steel body scores well but the innovative FreeSip spout requires liquid to travel through a built-in plastic straw and past a plastic spout before reaching your mouth. All plastic components are BPA free but BPA free does not mean entirely free of plastic-associated chemicals. A Good choice for daily water use.',
  82,
  'Good',
  'Based on Materials Science',
  '18/8 Stainless Steel',
  'BPA Free Plastic FreeSip Spout',
  'Yes',
  'Unknown',
  'https://www.amazon.com/s?k=Owala+FreeSip+24oz+Insulated+Stainless+Steel',
  'https://www.amazon.com/s?k=Owala+FreeSip+24oz+Insulated+Stainless+Steel',
  'https://www.target.com/p/owala-24oz-stainless-steel-freesip-water-bottle-out-of-the-blue/-/A-94894804',
  'https://www.walmart.com/ip/Owala-FreeSip-Insulated-Stainless-Steel-Water-Bottle-24-Ounce-Neo-Sage/39039593946',
  null,
  null,
  true
),
(
  'BlenderBottle Strada 24oz Stainless Steel Shaker',
  'BlenderBottle',
  'Kitchen',
  'Water Bottles and Drinkware',
  'The best PAC-conscious option for protein shake mixing. The body and interior are food grade stainless steel with a stainless steel mixing whisk — no plastic mixing ball. The lid and drinking spout are BPA free plastic with direct liquid contact which is the primary reason this scores in the Good tier. For anyone switching from a standard plastic shaker bottle this is a major upgrade.',
  84,
  'Good',
  'Based on Materials Science',
  '18/8 Stainless Steel',
  'BPA Free Plastic Lid and Spout',
  'Yes',
  'Unknown',
  'https://www.amazon.com/s?k=BlenderBottle+Strada+24oz+Stainless+Steel+Shaker',
  'https://www.amazon.com/s?k=BlenderBottle+Strada+24oz+Stainless+Steel+Shaker',
  'https://www.target.com/p/blender-bottle-usa-strada-24-oz-insulated-stainless-steel-shaker-with-loop-top/-/A-84310774',
  'https://www.walmart.com/ip/BlenderBottle-Strada-Insulated-Stainless-Steel-Shaker-Cup-with-Flip-Cap-24oz-Black/3735632777',
  null,
  null,
  true
),
(
  'Nalgene Sustain 32oz Wide Mouth Bottle',
  'Nalgene',
  'Kitchen',
  'Water Bottles and Drinkware',
  'The Nalgene Sustain is made from Tritan plastic which is BPA free and made from 50 percent post-consumer recycled material. However BPA free does not mean PAC free. Tritan plastic still contains other plastic-associated chemicals and the entire bottle including body and lid is plastic with 100 percent liquid contact. For consumers prioritizing PAC safety a stainless steel or glass alternative is strongly recommended.',
  48,
  'High Risk',
  'Based on Materials Science',
  'Tritan BPA Free Plastic',
  'Tritan BPA Free Plastic Lid',
  'Yes',
  'Unknown',
  'https://www.amazon.com/s?k=Nalgene+Sustain+32oz+Wide+Mouth+Bottle',
  'https://www.amazon.com/s?k=Nalgene+Sustain+32oz+Wide+Mouth+Bottle',
  'https://www.target.com/p/nalgene-32-fl-oz-50-post-consumer-recycled-plastic-wide-mouth-water-bottle/-/A-94673389',
  'https://www.walmart.com/ip/Nalgene-32oz-Wide-Mouth-Sustain-Bottle/2346956668',
  null,
  null,
  true
),
(
  'Bentgo Glass Containers with Tempered Glass Lids Set of 3',
  'Bentgo',
  'Kitchen',
  'Food Storage',
  'The Bentgo glass container set earns the highest score in our food storage category for one simple reason — both the containers AND the lids are made from tempered glass with a silicone seal. There is zero plastic contact with your food. No plastic lids sitting on food. No plastic packaging pressing against contents. Pure glass on all sides. For anyone serious about eliminating PAC exposure from food storage this is the benchmark recommendation.',
  97,
  'Excellent',
  'Based on Materials Science',
  'Tempered Glass',
  'Tempered Glass Lids with Silicone Seal',
  'Yes',
  'Yes',
  'https://www.amazon.com/s?k=Bentgo+Glass+Containers+Tempered+Glass+Lids',
  'https://www.amazon.com/s?k=Bentgo+Glass+Containers+Tempered+Glass+Lids',
  'https://www.target.com/p/bentgo-8pc-glass-leak-proof-meal-prep-set-coastal/-/A-88549111',
  'https://www.walmart.com/ip/Bentgo-Signature-Leak-Proof-Glass-Food-Storage-8-Piece-Set-1-Compartment-Plastic-Free-Containers-Airtight-Glass-Lids-BPA-Free-Microwave-Freezer-Oven/180399509959',
  null,
  null,
  true
),
(
  'Vtopmart Glass Food Storage Containers with Bamboo Lids 5 Pack',
  'Vtopmart',
  'Kitchen',
  'Food Storage',
  'Vtopmart''s bamboo lid glass containers are one of the cleanest food storage options available. Glass body with natural bamboo lids means zero synthetic polymer contact with your food. The silicone seal provides an airtight closure without introducing phthalates or bisphenols. Bamboo is a naturally antimicrobial material that does not leach any chemicals. An outstanding choice for meal prep and leftover storage.',
  96,
  'Excellent',
  'Based on Materials Science',
  'Borosilicate Glass',
  'Bamboo Lids with Silicone Seal',
  'Yes',
  'Yes',
  'https://www.amazon.com/Vtopmart-Containers-Storage-Microwave-Dishwasher/dp/B0FL7J1WC5',
  'https://www.amazon.com/Vtopmart-Containers-Storage-Microwave-Dishwasher/dp/B0FL7J1WC5',
  'https://www.target.com/p/vtopmart-8-pack-glass-food-storage-containers-with-airtight-lids-glass-meal-prep-containers-for-microwave-oven-freezer-and-dishwasher-bpa-free/-/A-1007307911',
  'https://www.walmart.com/ip/8pcs-Glass-Storage-Container-Set-with-Lids-Vtopmart-Meal-Prep-Containers-Airtight-Bento-Boxes-Gray/5116979629',
  null,
  null,
  true
),
(
  'Pyrex Simply Store 9 Pack Glass Food Storage Set',
  'Pyrex',
  'Kitchen',
  'Food Storage',
  'Pyrex is the most trusted name in glass food storage and the Simply Store set is a reliable everyday option. The glass containers score very high — tempered glass is completely inert and will never leach chemicals into your food. The plastic lids are BPA free but do have direct contact with food at the seal point. For hot foods allow to cool before placing the plastic lid on. A great entry point into glass food storage for anyone transitioning away from all-plastic containers.',
  87,
  'Good',
  'Based on Materials Science',
  'Tempered Glass',
  'BPA Free Plastic Lids',
  'Yes',
  'Unknown',
  'https://www.amazon.com/s?k=Pyrex+Simply+Store+9+Pack+Glass+Food+Storage+Set',
  'https://www.amazon.com/s?k=Pyrex+Simply+Store+9+Pack+Glass+Food+Storage+Set',
  'https://www.target.com/p/pyrex-simply-store-8-piece-glass-food-storage-set-4-vessels-and-4-lids-standard-packaging/-/A-88763345',
  'https://www.walmart.com/ip/Pyrex-18-piece-Glass-Food-Storage-Container-Set-with-Lids/2571045111',
  null,
  null,
  true
),
(
  'Glasslock Tempered Glass Containers with Locking Lids 18 Piece Set',
  'Glasslock',
  'Kitchen',
  'Food Storage',
  'Glasslock uses thick tempered glass throughout with a robust four tab locking lid system that creates an airtight seal. The silicone gasket does the sealing work which means less plastic to food contact than a typical snap lid design. The lids are BPA free plastic but the combination of tempered glass body and silicone-primary sealing keeps PAC risk low. A well-designed system that balances safety and everyday practicality.',
  90,
  'Excellent',
  'Based on Materials Science',
  'Tempered Glass',
  'BPA Free Plastic Locking Lids with Silicone Seal',
  'Yes',
  'Unknown',
  'https://www.amazon.com/s?k=Glasslock+Tempered+Glass+Containers+Locking+Lids',
  'https://www.amazon.com/s?k=Glasslock+Tempered+Glass+Containers+Locking+Lids',
  'https://www.target.com/p/glasslock-oven-and-microwave-safe-glass-food-storage-containers-18-piece-set/-/A-76476370',
  'https://www.walmart.com/ip/Glasslock-Oven-and-Microwave-Safe-Glass-Food-Storage-Containers-18-Piece-Set/16985494312',
  null,
  null,
  true
),
(
  'Rubbermaid Brilliance Glass Storage Set of 9',
  'Rubbermaid',
  'Kitchen',
  'Food Storage',
  'Rubbermaid Brilliance glass containers combine the safety of tempered glass with the convenience of a leak-proof plastic lid system. The glass body is fully inert and earns a high material score. The plastic lids are BPA free and designed to create a tight seal without extensive plastic to food contact. A practical choice for everyday use and a significant improvement over all-plastic food storage. The score reflects the plastic lid contact point which is the only meaningful PAC consideration in this set.',
  85,
  'Good',
  'Based on Materials Science',
  'Tempered Glass',
  'BPA Free Plastic Lids',
  'Yes',
  'Unknown',
  'https://www.amazon.com/s?k=Rubbermaid+Brilliance+Glass+Storage+Set+of+9',
  'https://www.amazon.com/s?k=Rubbermaid+Brilliance+Glass+Storage+Set+of+9',
  null,
  'https://www.walmart.com/ip/Rubbermaid-Brilliance-Glass-Food-Storage-Containers-8-Cup-Food-Containers-with-Lids-2-Pack/59633111413',
  null,
  null,
  true
),
(
  'Rubbermaid Brilliance Plastic Food Storage 10 Pack',
  'Rubbermaid',
  'Kitchen',
  'Food Storage',
  'The Rubbermaid Brilliance plastic set is one of the most popular food storage products in America and it scores High Risk on the PAC Safety Score. The containers are 100 percent plastic construction with direct food contact on all surfaces. While they are BPA free it is critical to understand that BPA free does not mean PAC free. Phthalate substitutes and other plastic-associated chemicals are still present in BPA free plastics. The risk increases significantly with fatty foods, acidic foods, and heat. Never microwave in these containers. Consider switching to glass alternatives for any food that will be stored for more than a few hours.',
  38,
  'High Risk',
  'Based on Materials Science',
  'BPA Free Plastic',
  'BPA Free Plastic Lids',
  'Yes',
  'Unknown',
  'https://www.amazon.com/s?k=Rubbermaid+Brilliance+Plastic+Food+Storage+10+Pack',
  'https://www.amazon.com/s?k=Rubbermaid+Brilliance+Plastic+Food+Storage+10+Pack',
  'https://www.target.com/p/rubbermaid-brilliance-10pc-plastic-food-storage-container-set/-/A-91597497',
  'https://www.walmart.com/ip/Rubbermaid-Brilliance-Leak-Proof-Food-Storage-Containers-10-Piece-Set/5429707814',
  null,
  null,
  true
),
(
  'Lodge 10.25 Inch Cast Iron Skillet',
  'Lodge',
  'Kitchen',
  'Cookware',
  'Cast iron is one of the oldest and safest cooking materials in existence. The Lodge skillet is pre-seasoned with natural oil and contains absolutely no synthetic coatings, no PTFE, no PFAS, no plastic components, and no chemical non-stick treatments. Cast iron does not leach plastic-associated chemicals. It is made in the USA and has been manufactured the same way for over a century. The cooking surface only gets better with age and use. For anyone concerned about PAC exposure from cookware this is an exceptional choice and one of our highest rated products.',
  96,
  'Excellent',
  'Based on Materials Science',
  'Cast Iron',
  'None',
  'Yes',
  'Yes',
  'https://www.amazon.com/s?k=Lodge+10.25+Inch+Cast+Iron+Skillet',
  'https://www.amazon.com/s?k=Lodge+10.25+Inch+Cast+Iron+Skillet',
  'https://www.target.com/p/lodge-10-25-cast-iron-skillet/-/A-10291925',
  'https://www.walmart.com/ip/Lodge-10-1-4-Cast-Iron-Skillet/596962815',
  null,
  null,
  true
),
(
  'All-Clad G5 Graphite Core Stainless Steel Skillet 12 Inch',
  'All-Clad',
  'Kitchen',
  'Cookware',
  'All-Clad is the professional standard in stainless steel cookware and the G5 is their flagship skillet. The cooking surface is 18/10 stainless steel which is completely inert and will never leach chemicals into food. No synthetic coatings of any kind. No PTFE. No PFAS. No plastic components. The graphite core delivers exceptional heat distribution without any compromise on material safety. An investment piece that scores in the Excellent tier and will last a lifetime.',
  94,
  'Excellent',
  'Based on Materials Science',
  '18/10 Stainless Steel',
  'Graphite Core',
  'Yes',
  'Yes',
  'https://www.amazon.com/s?k=All-Clad+G5+Graphite+Core+Stainless+Steel+Skillet+12+Inch',
  'https://www.amazon.com/s?k=All-Clad+G5+Graphite+Core+Stainless+Steel+Skillet+12+Inch',
  null,
  null,
  null,
  null,
  true
),
(
  'GreenPan Valencia Pro Ceramic Nonstick Skillet 10 Inch',
  'GreenPan',
  'Kitchen',
  'Cookware',
  'GreenPan is the most trusted PFAS-free nonstick brand on the market. The Thermolon ceramic nonstick coating contains no PTFE no PFOA no PFAS no lead and no cadmium. This is a significant improvement over traditional Teflon nonstick which contains chemicals linked to serious health concerns. The aluminum base is hard anodized which prevents any aluminum leaching. Score reflects that ceramic coatings are not as inert as bare stainless steel or cast iron but represent the safest nonstick option currently available.',
  78,
  'Good',
  'Based on Materials Science',
  'Hard Anodized Aluminum',
  'Ceramic Nonstick Coating',
  'Yes',
  'Yes',
  'https://www.amazon.com/s?k=GreenPan+Valencia+Pro+Ceramic+Nonstick+Skillet+10+Inch',
  'https://www.amazon.com/s?k=GreenPan+Valencia+Pro+Ceramic+Nonstick+Skillet+10+Inch',
  'https://www.target.com/p/greenpan-valencia-pro-10-34-ceramic-frypan-with-lid-black/-/A-86482934',
  'https://www.walmart.com/ip/GreenPan-Valencia-Pro-Healthy-Ceramic-Nonstick-10-Frypan/61343940717',
  null,
  null,
  true
),
(
  'HexClad Hybrid Nonstick 10 Inch Frying Pan',
  'HexClad',
  'Kitchen',
  'Cookware',
  'HexClad has become one of the most marketed cookware brands in the world but from a PAC safety perspective it warrants caution. The hybrid design combines stainless steel with a PTFE based nonstick coating in the hexagonal valleys of the cooking surface. PTFE is the chemical family that includes Teflon and while HexClad claims to be PFOA free the PTFE coating still raises concerns at high temperatures. Scores in the Caution tier because of the PTFE component. For low to medium heat cooking the risk is lower. For high heat cooking consider an uncoated stainless steel or cast iron alternative.',
  65,
  'Caution',
  'Based on Materials Science',
  'Stainless Steel and PTFE Hybrid',
  'Stainless Steel Handle',
  'Yes',
  'Unknown',
  'https://www.amazon.com/s?k=HexClad+Hybrid+Nonstick+10+Inch+Frying+Pan',
  'https://www.amazon.com/s?k=HexClad+Hybrid+Nonstick+10+Inch+Frying+Pan',
  null,
  'https://www.walmart.com/ip/HexClad-10-inch-Hybrid-Stainless-Steel-Frying-Pan-Nonstick/17619936018',
  null,
  null,
  true
),
(
  'T-Fal Ultimate Hard Anodized Nonstick Fry Pan Set 3 Piece',
  'T-Fal',
  'Kitchen',
  'Cookware',
  'T-Fal is one of the best selling nonstick cookware brands in America and one of the lowest scoring in our database. The nonstick coating is PTFE based which is the same chemical family as Teflon. At high temperatures PTFE coatings can begin to break down and release chemical compounds. The coating also scratches over time and scratched PTFE surfaces increase the risk of chemical migration into food. The Hard Anodized exterior is safe but the cooking surface is the concern. If you currently own T-Fal or similar PTFE nonstick cookware consider replacing with cast iron, stainless steel, or a certified PFAS-free ceramic alternative.',
  44,
  'High Risk',
  'Based on Materials Science',
  'Hard Anodized Aluminum',
  'PTFE Nonstick Coating',
  'Yes',
  'Unknown',
  'https://www.amazon.com/s?k=T-Fal+Ultimate+Hard+Anodized+Nonstick+Fry+Pan+Set+3+Piece',
  'https://www.amazon.com/s?k=T-Fal+Ultimate+Hard+Anodized+Nonstick+Fry+Pan+Set+3+Piece',
  'https://www.target.com/p/t-fal-ultimate-hard-anodized-3pk-fry-pan-set/-/A-87417764',
  'https://www.walmart.com/ip/T-fal-Ultimate-Hard-Anodized-Non-Stick-Cookware-3-Piece-Frypan-Set-8-inch-10-25-inch-and-12-inch-Grey/83563821619',
  null,
  null,
  true
),
(
  'Caraway Nonstick Ceramic Frying Pan 10.5 Inch',
  'Caraway',
  'Kitchen',
  'Cookware',
  'Caraway has become the go-to brand for design-conscious consumers wanting to move away from traditional Teflon cookware. Their ceramic coating is free from PTFE PFOA PFAS lead and cadmium. The brand is transparent about their materials and markets specifically to health-conscious consumers. Scores in the Good tier because ceramic coatings while much safer than PTFE are still a synthetic surface applied to an aluminum core. An excellent upgrade from traditional nonstick for everyday cooking.',
  80,
  'Good',
  'Based on Materials Science',
  'Aluminum Core',
  'Ceramic Nonstick Coating',
  'Yes',
  'Yes',
  'https://www.amazon.com/s?k=Caraway+Nonstick+Ceramic+Frying+Pan+10.5+Inch',
  'https://www.amazon.com/s?k=Caraway+Nonstick+Ceramic+Frying+Pan+10.5+Inch',
  'https://www.target.com/p/caraway-home-10-5-ceramic-fry-pan/-/A-84082481',
  null,
  null,
  null,
  true
),
(
  'Berglander 13 Piece Stainless Steel Cooking Utensil Set',
  'Berglander',
  'Kitchen',
  'Cooking Utensils',
  'The Berglander 13 piece set is an all stainless steel cooking utensil set with zero plastic food contact surfaces. Every piece including handles is stainless steel meaning there is no plastic anywhere near your food during cooking. Stainless steel does not leach chemicals does not react with acidic or fatty foods and does not degrade over time the way plastic utensils do. The mirror polish finish makes cleaning easy and the set includes everything a home cook needs. One of the best value high-scoring options in our utensils category.',
  93,
  'Excellent',
  'Based on Materials Science',
  '18/10 Stainless Steel',
  'Stainless Steel Handles',
  'Yes',
  'Yes',
  'https://www.amazon.com/s?k=Berglander+13+Piece+Stainless+Steel+Cooking+Utensil+Set',
  'https://www.amazon.com/s?k=Berglander+13+Piece+Stainless+Steel+Cooking+Utensil+Set',
  null,
  null,
  null,
  null,
  true
),
(
  'Viking 8 Piece Stainless Steel Cooking Utensil Set',
  'Viking',
  'Kitchen',
  'Cooking Utensils',
  'Built with 304 stainless steel and designed for professional level kitchens the Viking set features ergonomic hollow handles and excellent heat resistance. All cooking contact surfaces are stainless steel with zero plastic components anywhere in the set. 304 stainless steel is the professional food service grade and is completely non-reactive with all food types including acidic and fatty ingredients. An excellent choice for home cooks who want professional grade safety and durability.',
  92,
  'Excellent',
  'Based on Materials Science',
  '304 Stainless Steel',
  'Hollow Stainless Steel Handles',
  'Yes',
  'Yes',
  'https://www.amazon.com/s?k=Viking+8+Piece+Stainless+Steel+Cooking+Utensil+Set',
  'https://www.amazon.com/s?k=Viking+8+Piece+Stainless+Steel+Cooking+Utensil+Set',
  null,
  null,
  null,
  null,
  true
),
(
  'OXO Good Grips 6 Piece Stainless Steel Utensil Set',
  'OXO',
  'Kitchen',
  'Cooking Utensils',
  'OXO Good Grips is one of the most trusted kitchen brands for quality and ergonomics. The stainless steel cooking surfaces score very well — your food only ever contacts stainless steel. The score deduction comes from the soft grip plastic handles which contain BPA free plastic. The handles do not contact food during cooking but they are held in hand for extended periods which creates dermal exposure to plastic materials. An excellent choice for everyday cooking with a minor consideration around handle material.',
  85,
  'Good',
  'Based on Materials Science',
  'Stainless Steel',
  'Soft Grip Plastic Handles',
  'Yes',
  'Unknown',
  'https://www.amazon.com/s?k=OXO+Good+Grips+6+Piece+Stainless+Steel+Utensil+Set',
  'https://www.amazon.com/s?k=OXO+Good+Grips+6+Piece+Stainless+Steel+Utensil+Set',
  null,
  'https://www.walmart.com/ip/OXO-Good-Grips-Stainless-Steel-Prep-Serve-Kitchen-Tool-6pc-Set/2019798401',
  null,
  null,
  true
),
(
  'Kikcoin 10 Piece Natural Teak Wooden Cooking Utensil Set',
  'Kikcoin',
  'Kitchen',
  'Cooking Utensils',
  'Natural teak wood utensils are one of the oldest and safest cooking tool materials in existence. Teak contains zero synthetic chemicals zero plastics and zero coatings. It is naturally antimicrobial, gentle on cookware surfaces, and completely inert. A set of natural wood utensils scores nearly as high as all stainless steel because there is simply nothing in the material that could leach plastic-associated chemicals. An excellent choice especially for nonstick cookware where metal utensils can scratch the surface and accelerate coating degradation.',
  95,
  'Excellent',
  'Based on Materials Science',
  'Natural Teak Wood',
  'None',
  'Yes',
  'Yes',
  'https://www.amazon.com/s?k=Kikcoin+10+Piece+Natural+Teak+Wooden+Cooking+Utensil+Set',
  'https://www.amazon.com/s?k=Kikcoin+10+Piece+Natural+Teak+Wooden+Cooking+Utensil+Set',
  null,
  null,
  null,
  null,
  true
),
(
  'Joseph Joseph Elevate Nylon Cooking Utensil Set 6 Piece',
  'Joseph Joseph',
  'Kitchen',
  'Cooking Utensils',
  'Nylon cooking utensils are one of the higher risk items in the average kitchen. The nylon plastic cooking surfaces come into direct contact with hot food during cooking and heat is exactly the condition under which plastic-associated chemical migration is most likely to occur. BPA free status does not eliminate the risk from other phthalate compounds and plastic chemicals present in nylon formulations. Scratched and worn nylon utensils increase the risk further. If you currently use nylon or other plastic utensils for cooking replacing them with stainless steel or natural wood is one of the highest impact PAC reduction swaps you can make.',
  35,
  'High Risk',
  'Based on Materials Science',
  'Nylon Plastic',
  'Plastic Handles',
  'Yes',
  'Unknown',
  'https://www.amazon.com/s?k=Joseph+Joseph+Elevate+Nylon+Cooking+Utensil+Set+6+Piece',
  'https://www.amazon.com/s?k=Joseph+Joseph+Elevate+Nylon+Cooking+Utensil+Set+6+Piece',
  'https://www.target.com/p/joseph-joseph-elevate-6-piece-carousel-utensil-set/-/A-84793467',
  'https://www.walmart.com/ip/Joseph-Joseph-Elevate-6-Piece-Kitchen-Utensil-Set-Multicolored/14508906925',
  null,
  null,
  true
),
(
  'Silicone Cooking Utensil Set AOTHOD 446F Heat Resistant 8 Piece',
  'AOTHOD',
  'Kitchen',
  'Cooking Utensils',
  'Food grade silicone utensils occupy a middle ground in PAC safety. Silicone is not a plastic in the traditional sense and does not contain phthalates or bisphenols when made to food grade standards. However silicone quality varies significantly between manufacturers and low quality silicone can still leach concerning chemicals at high temperatures. The stainless steel handles are a positive feature. Scores in the Caution tier because silicone safety depends heavily on the quality of the specific formulation and this cannot be verified from material claims alone. A reasonable choice if you prefer flexible utensils but stainless steel or wood are safer first choices.',
  62,
  'Caution',
  'Based on Materials Science',
  'Food Grade Silicone',
  'Stainless Steel Core Handles',
  'Yes',
  'Unknown',
  'https://www.amazon.com/s?k=AOTHOD+Silicone+Cooking+Utensil+Set+446F+Heat+Resistant+8+Piece',
  'https://www.amazon.com/s?k=AOTHOD+Silicone+Cooking+Utensil+Set+446F+Heat+Resistant+8+Piece',
  null,
  null,
  null,
  null,
  true
),
(
  'Blueland Powder Dish Soap Refillable System',
  'Blueland',
  'Kitchen',
  'Dish Soap',
  'Blueland is one of the highest scoring dish soaps in our database for two reasons. First the formula is explicitly free from phthalates parabens SLS SLES synthetic fragrances and phosphates — every ingredient category that drives PAC exposure in conventional dish soaps is absent. Second the packaging is a refillable system that eliminates the plastic bottle entirely. Blueland holds certifications from B Corp, Climate Neutral, EPA Safer Choice, MADE SAFE, and EWG Verified. This is as clean as dish soap gets and the refillable system means you are reducing plastic exposure not just in the formula but in the packaging too.',
  91,
  'Excellent',
  'Based on Materials Science',
  'Plant Based Surfactants',
  'None',
  'Yes',
  'Yes',
  'https://www.amazon.com/s?k=Blueland+Powder+Dish+Soap+Refillable',
  'https://www.amazon.com/s?k=Blueland+Powder+Dish+Soap+Refillable',
  null,
  null,
  null,
  null,
  true
),
(
  'Puracy Natural Liquid Dish Soap Fresh Citrus',
  'Puracy',
  'Kitchen',
  'Dish Soap',
  'Puracy is a premium plant-based dish soap formulated by a team of PhDs with families in mind. The formula is free from phthalates parabens SLS SLES synthetic fragrances and harsh chemicals. It is biodegradable and gentle on skin while remaining effective on grease. Puracy is transparent about every ingredient and the formula is safe for baby bottles and sensitive skin. The score reflects excellent ingredient safety with a minor deduction for the plastic bottle packaging which is recyclable but not refillable like some higher-scoring alternatives.',
  88,
  'Good',
  'Based on Materials Science',
  'Plant Based Surfactants',
  'None',
  'Yes',
  'Yes',
  'https://www.amazon.com/s?k=Puracy+Natural+Liquid+Dish+Soap+Fresh+Citrus',
  'https://www.amazon.com/s?k=Puracy+Natural+Liquid+Dish+Soap+Fresh+Citrus',
  null,
  null,
  null,
  null,
  true
),
(
  'Seventh Generation Free and Clear Dish Soap',
  'Seventh Generation',
  'Kitchen',
  'Dish Soap',
  'Seventh Generation Free and Clear is one of the most accessible non-toxic dish soaps available in mainstream grocery stores and online. The fragrance-free formula uses plant-derived surfactants and avoids the phthalate-containing synthetic fragrances that make conventional dish soaps a hidden PAC exposure source. EWG rates this product favorably. A reliable everyday choice for households transitioning away from conventional dish soaps like Dawn which contains synthetic fragrance and other concerning ingredients.',
  82,
  'Good',
  'Based on Materials Science',
  'Plant Based Surfactants',
  'None',
  'Yes',
  'Yes',
  'https://www.amazon.com/s?k=Seventh+Generation+Free+Clear+Dish+Soap',
  'https://www.amazon.com/s?k=Seventh+Generation+Free+Clear+Dish+Soap',
  'https://www.target.com/p/seventh-generation-free-38-clear-liquid-dish-soap-19-fl-oz/-/A-81400492',
  'https://www.walmart.com/ip/Seventh-Generation-Dish-Soap-Liquid-Free-Clear-19-oz/13150863529',
  null,
  null,
  true
),
(
  'Branch Basics Multi Purpose Concentrate for Dish Washing',
  'Branch Basics',
  'Kitchen',
  'Dish Soap',
  'Branch Basics is a highly concentrated multi-purpose cleaner that many households use for hand dishwashing by diluting appropriately. The formula relies on a simple blend of plant-derived surfactants and minerals with no synthetic fragrances no phthalates no parabens and no SLS. The ingredient list is short clear and completely transparent. The concentrate model means less plastic packaging waste per use compared to conventional dish soaps. Branch Basics is especially popular in health-conscious households and scores highly on both ingredient safety and packaging efficiency.',
  90,
  'Excellent',
  'Based on Materials Science',
  'Plant Based Surfactants and Minerals',
  'None',
  'Yes',
  'Yes',
  'https://www.amazon.com/s?k=Branch+Basics+Concentrate+Dish+Washing',
  'https://www.amazon.com/s?k=Branch+Basics+Concentrate+Dish+Washing',
  null,
  null,
  null,
  null,
  true
),
(
  'Dawn Ultra Original Scent Dishwashing Liquid',
  'Dawn',
  'Kitchen',
  'Dish Soap',
  'Dawn is the best selling dish soap in America and one of the lowest scoring products in our database. The EWG gave Dawn Ultra a D rating for its ingredient profile. The formula contains synthetic fragrance which is a known phthalate delivery mechanism — the term fragrance on a label can represent hundreds of undisclosed chemicals including endocrine-disrupting phthalates. Dawn also contains SLS and synthetic dyes derived from petroleum. Your hands are submerged in dish soap for several minutes at a time making dermal absorption a significant exposure pathway. Switching from Dawn to any of our Good or Excellent tier alternatives is one of the easiest and highest-impact PAC reduction swaps you can make in your kitchen.',
  22,
  'High Risk',
  'Based on Materials Science',
  'Synthetic Surfactants',
  'Synthetic Fragrance',
  'Unknown',
  'No',
  'https://www.amazon.com/s?k=Dawn+Ultra+Original+Scent+Dishwashing+Liquid',
  'https://www.amazon.com/s?k=Dawn+Ultra+Original+Scent+Dishwashing+Liquid',
  'https://www.target.com/p/dawn-ultra-original-scent-dishwashing-liquid-dish-soap/-/A-78259812',
  'https://www.walmart.com/ip/Dawn-Ultra-Dish-Soap-Dishwashing-Liquid-Original-Scent-28-fl-oz/843280151',
  null,
  null,
  true
),
(
  'Meliora Dish Soap Bar Zero Waste',
  'Meliora',
  'Kitchen',
  'Dish Soap',
  'Meliora''s dish soap bar is one of the cleanest dish cleaning options on the market and eliminates plastic bottle packaging entirely. The formula contains no phthalates no parabens no synthetic fragrances no SLS and no petroleum derived ingredients. It is B Corp certified and MADE SAFE certified — two of the most rigorous third party safety certifications available. The zero waste format means this product scores highly not just on ingredient safety but on packaging impact. A bar of dish soap lasting the equivalent of multiple plastic bottles makes this one of the most environmentally and chemically responsible choices in our database.',
  94,
  'Excellent',
  'Based on Materials Science',
  'Plant Based Saponified Oils',
  'None',
  'Yes',
  'Yes',
  'https://www.amazon.com/s?k=Meliora+Dish+Soap+Bar+Zero+Waste',
  'https://www.amazon.com/s?k=Meliora+Dish+Soap+Bar+Zero+Waste',
  null,
  null,
  null,
  null,
  true
);

-- V2.3.4: materials-science scope — hide dish soap / formulation products from public catalog
update public.products
set active = false
where trim(coalesce(subcategory, '')) = 'Dish Soap';

insert into public.categories (category_name, subcategory_name, description, display_order)
select
  p.category,
  p.subcategory,
  null,
  row_number() over (order by p.category, p.subcategory)
from (
  select distinct category, subcategory
  from public.products
  where category is not null
    and subcategory is not null
    and active = true
) p
order by p.category, p.subcategory;

commit;

